firstinteger = int(input("Enter first integer:"))
secondinteger = int(input("Enter second integer:"))
print(firstinteger + secondinteger)
print(secondinteger - firstinteger)
print(firstinteger/secondinteger)
print(firstinteger%secondinteger)
print(firstinteger**secondinteger)